import "./globals.css";
import { Inter, Francois_One, Graduate } from "next/font/google";
// fontawesome configuration
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});
const francois_one = Francois_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-francois-one",
});
const graduate = Graduate({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-graduate",
});

export const metadata = {
  title: "Giyanto-Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake" class="scroll-smooth">
      <body
        className={`${inter.variable} ${graduate.variable} ${francois_one.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
